seyon_phpbb3_admin:
  table_prefix: phpbb_
  
doctrine:
    dbal:
      default_connection: default
      connections:
        seyon_phpbb3:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            seyon_phpbb3:
                connection:       seyon_phpbb3
                mappings:
                    SeyonPHPBB3AdminBundle: ~