services:
    seyon_phpbb3_reader:
        class:        Seyon\PHPBB3\AdminBundle\Service\Reader
        arguments:    ['@doctrine.orm.entity_manager', '@service_container', '@security.context']
    seyon_phpbb3_twig_reader:
        class: Seyon\PHPBB3\AdminBundle\Twig\ReaderExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }