services:
    seyon_phpbb3_table_prefix:
        class: Seyon\PHPBB3\AdminBundle\EventListener\DoctrineNameListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: seyon_phpbb3 }
    seyon_phpbb3_reader:
        class:        Seyon\PHPBB3\AdminBundle\Service\Reader
        calls:
            - [setEM, ["@doctrine.orm.seyon_phpbb3_entity_manager"]]
            - [setContainer, ["@service_container"]]
            - [setSecurity, ["@security.context"]]
    seyon_phpbb3_twig_reader:
        class: Seyon\PHPBB3\AdminBundle\Twig\ReaderExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }