services:
    seyon_phpbb3_reader:
        class:        Seyon\PHPBB3\AdminBundle\Service\Reader
        arguments:    ['@doctrine.orm.entity_manager', '@service_container', '@security.context']
    seyon_phpbb3_twig_reader:
        class: Seyon\PHPBB3\AdminBundle\Twig\ReaderExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    seyon_phpbb3_table_prefix:
        class: Seyon\PHPBB3\AdminBundle\EventListener\DoctrineNameListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: name, connection: seyon_phpbb3 }